package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteQuaternion extends StructObject {
	@Field(0) 
	public float x() {
		return this.io.getFloatField(this, 0);
	}
	@Field(0) 
	public NiteQuaternion x(float x) {
		this.io.setFloatField(this, 0, x);
		return this;
	}
	@Field(1) 
	public float y() {
		return this.io.getFloatField(this, 1);
	}
	@Field(1) 
	public NiteQuaternion y(float y) {
		this.io.setFloatField(this, 1, y);
		return this;
	}
	@Field(2) 
	public float z() {
		return this.io.getFloatField(this, 2);
	}
	@Field(2) 
	public NiteQuaternion z(float z) {
		this.io.setFloatField(this, 2, z);
		return this;
	}
	@Field(3) 
	public float w() {
		return this.io.getFloatField(this, 3);
	}
	@Field(3) 
	public NiteQuaternion w(float w) {
		this.io.setFloatField(this, 3, w);
		return this;
	}
	public NiteQuaternion() {
		super();
	}
	public NiteQuaternion(Pointer pointer) {
		super(pointer);
	}
}
