package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteHandData extends StructObject {
	/** C type : NiteHandId */
	@Field(0) 
	public short id() {
		return this.io.getShortField(this, 0);
	}
	/** C type : NiteHandId */
	@Field(0) 
	public NiteHandData id(short id) {
		this.io.setShortField(this, 0, id);
		return this;
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NitePoint3f position() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NiteHandData position(NitePoint3f position) {
		this.io.setNativeObjectField(this, 1, position);
		return this;
	}
	@Field(2) 
	public int state() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public NiteHandData state(int state) {
		this.io.setIntField(this, 2, state);
		return this;
	}
	public NiteHandData() {
		super();
	}
	public NiteHandData(Pointer pointer) {
		super(pointer);
	}
}
