package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteVersion extends StructObject {
	@Field(0) 
	public int major() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public NiteVersion major(int major) {
		this.io.setIntField(this, 0, major);
		return this;
	}
	@Field(1) 
	public int minor() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public NiteVersion minor(int minor) {
		this.io.setIntField(this, 1, minor);
		return this;
	}
	@Field(2) 
	public int maintenance() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public NiteVersion maintenance(int maintenance) {
		this.io.setIntField(this, 2, maintenance);
		return this;
	}
	@Field(3) 
	public int build() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public NiteVersion build(int build) {
		this.io.setIntField(this, 3, build);
		return this;
	}
	public NiteVersion() {
		super();
	}
	public NiteVersion(Pointer pointer) {
		super(pointer);
	}
}
