package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteBoundingBox extends StructObject {
	/** C type : NitePoint3f */
	@Field(0) 
	public NitePoint3f min() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : NitePoint3f */
	@Field(0) 
	public NiteBoundingBox min(NitePoint3f min) {
		this.io.setNativeObjectField(this, 0, min);
		return this;
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NitePoint3f max() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NiteBoundingBox max(NitePoint3f max) {
		this.io.setNativeObjectField(this, 1, max);
		return this;
	}
	public NiteBoundingBox() {
		super();
	}
	public NiteBoundingBox(Pointer pointer) {
		super(pointer);
	}
}
