package interactivespaces.service.image.depth.internal.openni2.libraries;
import interactivespaces.service.image.depth.internal.openni2.libraries.NiTE2Library.NiteSkeletonState;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteSkeleton extends StructObject {
	/** C type : NiteSkeletonJoint[15] */
	@Array({15}) 
	@Field(0) 
	public Pointer<NiteSkeletonJoint > joints() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : NiteSkeletonState */
	@Field(1) 
	public IntValuedEnum<NiteSkeletonState > state() {
		return this.io.getEnumField(this, 1);
	}
	/** C type : NiteSkeletonState */
	@Field(1) 
	public NiteSkeleton state(IntValuedEnum<NiteSkeletonState > state) {
		this.io.setEnumField(this, 1, state);
		return this;
	}
	public NiteSkeleton() {
		super();
	}
	public NiteSkeleton(Pointer pointer) {
		super(pointer);
	}
}
