package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteUserTrackerFrame extends StructObject {
	/** Number of users */
	@Field(0) 
	public int userCount() {
		return this.io.getIntField(this, 0);
	}
	/** Number of users */
	@Field(0) 
	public NiteUserTrackerFrame userCount(int userCount) {
		this.io.setIntField(this, 0, userCount);
		return this;
	}
	/**
	 * List of users<br>
	 * C type : NiteUserData*
	 */
	@Field(1) 
	public Pointer<NiteUserData > pUser() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * List of users<br>
	 * C type : NiteUserData*
	 */
	@Field(1) 
	public NiteUserTrackerFrame pUser(Pointer<NiteUserData > pUser) {
		this.io.setPointerField(this, 1, pUser);
		return this;
	}
	/**
	 * Scene segmentation map<br>
	 * C type : NiteUserMap
	 */
	@Field(2) 
	public NiteUserMap userMap() {
		return this.io.getNativeObjectField(this, 2);
	}
	/**
	 * Scene segmentation map<br>
	 * C type : NiteUserMap
	 */
	@Field(2) 
	public NiteUserTrackerFrame userMap(NiteUserMap userMap) {
		this.io.setNativeObjectField(this, 2, userMap);
		return this;
	}
	/**
	 * The depth frame from which this data was learned<br>
	 * C type : OniFrame*
	 */
	@Field(3) 
	public Pointer<OniFrame > pDepthFrame() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * The depth frame from which this data was learned<br>
	 * C type : OniFrame*
	 */
	@Field(3) 
	public NiteUserTrackerFrame pDepthFrame(Pointer<OniFrame > pDepthFrame) {
		this.io.setPointerField(this, 3, pDepthFrame);
		return this;
	}
	@Field(4) 
	public long timestamp() {
		return this.io.getLongField(this, 4);
	}
	@Field(4) 
	public NiteUserTrackerFrame timestamp(long timestamp) {
		this.io.setLongField(this, 4, timestamp);
		return this;
	}
	@Field(5) 
	public int frameIndex() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public NiteUserTrackerFrame frameIndex(int frameIndex) {
		this.io.setIntField(this, 5, frameIndex);
		return this;
	}
	/** Confidence of the floor plane */
	@Field(6) 
	public float floorConfidence() {
		return this.io.getFloatField(this, 6);
	}
	/** Confidence of the floor plane */
	@Field(6) 
	public NiteUserTrackerFrame floorConfidence(float floorConfidence) {
		this.io.setFloatField(this, 6, floorConfidence);
		return this;
	}
	/**
	 * Floor plane<br>
	 * C type : NitePlane
	 */
	@Field(7) 
	public NitePlane floor() {
		return this.io.getNativeObjectField(this, 7);
	}
	/**
	 * Floor plane<br>
	 * C type : NitePlane
	 */
	@Field(7) 
	public NiteUserTrackerFrame floor(NitePlane floor) {
		this.io.setNativeObjectField(this, 7, floor);
		return this;
	}
	public NiteUserTrackerFrame() {
		super();
	}
	public NiteUserTrackerFrame(Pointer pointer) {
		super(pointer);
	}
}
