package interactivespaces.service.image.depth.internal.openni2.libraries;
import interactivespaces.service.image.depth.internal.openni2.libraries.NiTE2Library.NiteGestureType;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteGestureData extends StructObject {
	/** C type : NiteGestureType */
	@Field(0) 
	public IntValuedEnum<NiteGestureType > type() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : NiteGestureType */
	@Field(0) 
	public NiteGestureData type(IntValuedEnum<NiteGestureType > type) {
		this.io.setEnumField(this, 0, type);
		return this;
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NitePoint3f currentPosition() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : NitePoint3f */
	@Field(1) 
	public NiteGestureData currentPosition(NitePoint3f currentPosition) {
		this.io.setNativeObjectField(this, 1, currentPosition);
		return this;
	}
	@Field(2) 
	public int state() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public NiteGestureData state(int state) {
		this.io.setIntField(this, 2, state);
		return this;
	}
	public NiteGestureData() {
		super();
	}
	public NiteGestureData(Pointer pointer) {
		super(pointer);
	}
}
