package interactivespaces.service.image.depth.internal.openni2.libraries;
import interactivespaces.service.image.depth.internal.openni2.libraries.OpenNI2Library.OniGeneralCallback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteUserTrackerCallbacks extends StructObject {
	/** C type : OniGeneralCallback */
	@Field(0) 
	public Pointer<OniGeneralCallback > readyForNextFrame() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : OniGeneralCallback */
	@Field(0) 
	public NiteUserTrackerCallbacks readyForNextFrame(Pointer<OniGeneralCallback > readyForNextFrame) {
		this.io.setPointerField(this, 0, readyForNextFrame);
		return this;
	}
	public NiteUserTrackerCallbacks() {
		super();
	}
	public NiteUserTrackerCallbacks(Pointer pointer) {
		super(pointer);
	}
}
