package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : NiteCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("NiTE2") 
public class NiteUserData extends StructObject {
	/** C type : NiteUserId */
	@Field(0) 
	public short id() {
		return this.io.getShortField(this, 0);
	}
	/** C type : NiteUserId */
	@Field(0) 
	public NiteUserData id(short id) {
		this.io.setShortField(this, 0, id);
		return this;
	}
	/** C type : NiteBoundingBox */
	@Field(1) 
	public NiteBoundingBox boundingBox() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : NiteBoundingBox */
	@Field(1) 
	public NiteUserData boundingBox(NiteBoundingBox boundingBox) {
		this.io.setNativeObjectField(this, 1, boundingBox);
		return this;
	}
	/** C type : NitePoint3f */
	@Field(2) 
	public NitePoint3f centerOfMass() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : NitePoint3f */
	@Field(2) 
	public NiteUserData centerOfMass(NitePoint3f centerOfMass) {
		this.io.setNativeObjectField(this, 2, centerOfMass);
		return this;
	}
	@Field(3) 
	public int state() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public NiteUserData state(int state) {
		this.io.setIntField(this, 3, state);
		return this;
	}
	/** C type : NiteSkeleton */
	@Field(4) 
	public NiteSkeleton skeleton() {
		return this.io.getNativeObjectField(this, 4);
	}
	/** C type : NiteSkeleton */
	@Field(4) 
	public NiteUserData skeleton(NiteSkeleton skeleton) {
		this.io.setNativeObjectField(this, 4, skeleton);
		return this;
	}
	/** C type : NitePoseData[2] */
	@Array({2}) 
	@Field(5) 
	public Pointer<NitePoseData > poses() {
		return this.io.getPointerField(this, 5);
	}
	public NiteUserData() {
		super();
	}
	public NiteUserData(Pointer pointer) {
		super(pointer);
	}
}
