package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : OniCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenNI2") 
public class OniCropping extends StructObject {
	@Field(0) 
	public int enabled() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public OniCropping enabled(int enabled) {
		this.io.setIntField(this, 0, enabled);
		return this;
	}
	@Field(1) 
	public int originX() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public OniCropping originX(int originX) {
		this.io.setIntField(this, 1, originX);
		return this;
	}
	@Field(2) 
	public int originY() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public OniCropping originY(int originY) {
		this.io.setIntField(this, 2, originY);
		return this;
	}
	@Field(3) 
	public int width() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public OniCropping width(int width) {
		this.io.setIntField(this, 3, width);
		return this;
	}
	@Field(4) 
	public int height() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public OniCropping height(int height) {
		this.io.setIntField(this, 4, height);
		return this;
	}
	public OniCropping() {
		super();
	}
	public OniCropping(Pointer pointer) {
		super(pointer);
	}
}
