package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : OniCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenNI2") 
public class OniDeviceInfo extends StructObject {
	/** C type : char[256] */
	@Array({256}) 
	@Field(0) 
	public Pointer<Byte > uri() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char[256] */
	@Array({256}) 
	@Field(1) 
	public Pointer<Byte > vendor() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : char[256] */
	@Array({256}) 
	@Field(2) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 2);
	}
	@Field(3) 
	public short usbVendorId() {
		return this.io.getShortField(this, 3);
	}
	@Field(3) 
	public OniDeviceInfo usbVendorId(short usbVendorId) {
		this.io.setShortField(this, 3, usbVendorId);
		return this;
	}
	@Field(4) 
	public short usbProductId() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public OniDeviceInfo usbProductId(short usbProductId) {
		this.io.setShortField(this, 4, usbProductId);
		return this;
	}
	public OniDeviceInfo() {
		super();
	}
	public OniDeviceInfo(Pointer pointer) {
		super(pointer);
	}
}
