package interactivespaces.service.image.depth.internal.openni2.libraries;
import interactivespaces.service.image.depth.internal.openni2.libraries.OpenNI2Library.OniSensorType;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : OniCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenNI2") 
public class OniFrame extends StructObject {
	@Field(0) 
	public int dataSize() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public OniFrame dataSize(int dataSize) {
		this.io.setIntField(this, 0, dataSize);
		return this;
	}
	/** C type : void* */
	@Field(1) 
	public Pointer<? > data() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : void* */
	@Field(1) 
	public OniFrame data(Pointer<? > data) {
		this.io.setPointerField(this, 1, data);
		return this;
	}
	/** C type : OniSensorType */
	@Field(2) 
	public IntValuedEnum<OniSensorType > sensorType() {
		return this.io.getEnumField(this, 2);
	}
	/** C type : OniSensorType */
	@Field(2) 
	public OniFrame sensorType(IntValuedEnum<OniSensorType > sensorType) {
		this.io.setEnumField(this, 2, sensorType);
		return this;
	}
	@CLong 
	@Field(3) 
	public long timestamp() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public OniFrame timestamp(long timestamp) {
		this.io.setCLongField(this, 3, timestamp);
		return this;
	}
	@Field(4) 
	public int frameIndex() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public OniFrame frameIndex(int frameIndex) {
		this.io.setIntField(this, 4, frameIndex);
		return this;
	}
	@Field(5) 
	public int width() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public OniFrame width(int width) {
		this.io.setIntField(this, 5, width);
		return this;
	}
	@Field(6) 
	public int height() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public OniFrame height(int height) {
		this.io.setIntField(this, 6, height);
		return this;
	}
	/** C type : OniVideoMode */
	@Field(7) 
	public OniVideoMode videoMode() {
		return this.io.getNativeObjectField(this, 7);
	}
	/** C type : OniVideoMode */
	@Field(7) 
	public OniFrame videoMode(OniVideoMode videoMode) {
		this.io.setNativeObjectField(this, 7, videoMode);
		return this;
	}
	/** C type : OniBool */
	@Field(8) 
	public int croppingEnabled() {
		return this.io.getIntField(this, 8);
	}
	/** C type : OniBool */
	@Field(8) 
	public OniFrame croppingEnabled(int croppingEnabled) {
		this.io.setIntField(this, 8, croppingEnabled);
		return this;
	}
	@Field(9) 
	public int cropOriginX() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public OniFrame cropOriginX(int cropOriginX) {
		this.io.setIntField(this, 9, cropOriginX);
		return this;
	}
	@Field(10) 
	public int cropOriginY() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public OniFrame cropOriginY(int cropOriginY) {
		this.io.setIntField(this, 10, cropOriginY);
		return this;
	}
	@Field(11) 
	public int stride() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public OniFrame stride(int stride) {
		this.io.setIntField(this, 11, stride);
		return this;
	}
	public OniFrame() {
		super();
	}
	public OniFrame(Pointer pointer) {
		super(pointer);
	}
}
