package interactivespaces.service.image.depth.internal.openni2.libraries;
import interactivespaces.service.image.depth.internal.openni2.libraries.OpenNI2Library.OniPixelFormat;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : OniCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenNI2") 
public class OniVideoMode extends StructObject {
	/** C type : OniPixelFormat */
	@Field(0) 
	public IntValuedEnum<OniPixelFormat > pixelFormat() {
		return this.io.getEnumField(this, 0);
	}
	/** C type : OniPixelFormat */
	@Field(0) 
	public OniVideoMode pixelFormat(IntValuedEnum<OniPixelFormat > pixelFormat) {
		this.io.setEnumField(this, 0, pixelFormat);
		return this;
	}
	@Field(1) 
	public int resolutionX() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public OniVideoMode resolutionX(int resolutionX) {
		this.io.setIntField(this, 1, resolutionX);
		return this;
	}
	@Field(2) 
	public int resolutionY() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public OniVideoMode resolutionY(int resolutionY) {
		this.io.setIntField(this, 2, resolutionY);
		return this;
	}
	@Field(3) 
	public int fps() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public OniVideoMode fps(int fps) {
		this.io.setIntField(this, 3, fps);
		return this;
	}
	public OniVideoMode() {
		super();
	}
	public OniVideoMode(Pointer pointer) {
		super(pointer);
	}
}
