package interactivespaces.service.image.depth.internal.openni2.libraries;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : OniCTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenNI2") 
public class OniYUV422DoublePixel extends StructObject {
	/** First chrominance value for two pixels, stored as blue luminance difference signal. */
	@Field(0) 
	public byte u() {
		return this.io.getByteField(this, 0);
	}
	/** First chrominance value for two pixels, stored as blue luminance difference signal. */
	@Field(0) 
	public OniYUV422DoublePixel u(byte u) {
		this.io.setByteField(this, 0, u);
		return this;
	}
	/** Overall luminance value of first pixel. */
	@Field(1) 
	public byte y1() {
		return this.io.getByteField(this, 1);
	}
	/** Overall luminance value of first pixel. */
	@Field(1) 
	public OniYUV422DoublePixel y1(byte y1) {
		this.io.setByteField(this, 1, y1);
		return this;
	}
	/** Second chrominance value for two pixels, stored as red luminance difference signal. */
	@Field(2) 
	public byte v() {
		return this.io.getByteField(this, 2);
	}
	/** Second chrominance value for two pixels, stored as red luminance difference signal. */
	@Field(2) 
	public OniYUV422DoublePixel v(byte v) {
		this.io.setByteField(this, 2, v);
		return this;
	}
	/** Overall luminance value of second pixel. */
	@Field(3) 
	public byte y2() {
		return this.io.getByteField(this, 3);
	}
	/** Overall luminance value of second pixel. */
	@Field(3) 
	public OniYUV422DoublePixel y2(byte y2) {
		this.io.setByteField(this, 3, y2);
		return this;
	}
	public OniYUV422DoublePixel() {
		super();
	}
	public OniYUV422DoublePixel(Pointer pointer) {
		super(pointer);
	}
}
